delete bin toilet for banner

diff --git a/ssha b/ssha
--- a/ssha
+++ b/ssha
@@ -60,15 +60,31 @@ if [ -d $DeletedFolder ];then
 fi
 
 ##############################
-# FUNCTION # list servers
+# FUNCTION # bcount
 ##############################
-function list() {
-    printf "\n${Blue}Index\tDescription\tHost\tPort\tUsername\tPassword|SecretKeyFile${ResetColor}\n"
-    for ((i=0;i<"$server_list_length";i++));do
-        servers=(${server_list[$i]})
-        printf "${servers[0]}\t${servers[1]}\t${servers[2]}\t${servers[3]}\t${servers[4]}\t${servers[5]}" | toilet -f term -F border -t
-    done
-    exit 0
+bcount()
+{
+	Caract="$@"
+	NbCaract=${#Caract}
+	NbCaract=$((NbCaract +$Fit))
+}
+
+##############################
+# FUNCTION # banner
+##############################
+banner()
+{
+    if [[ $Close == 1 ]];then
+    # close middle line
+	printf "+" && printf %$NbCaract\s | tr " " "-" && printf "+\n|  "
+	printf "$@"
+	printf "  |\n+" && printf %$NbCaract\s | tr " " "-" && printf "+\n"
+    else
+    # not close middle line
+	printf "+" && printf %$NbCaract\s | tr " " "-" && printf "+\n|  "
+	printf "$@"
+	printf "\n+" && printf %$NbCaract\s | tr " " "-" && printf "+\n"
+    fi
 }
 
 ##############################
@@ -81,36 +97,15 @@ printf "${Blue}ssha${ResetColor} [${Blue}-h${ResetColor}] [${Green}-l${ResetColo
 }
 
 ##############################
-# FUNCTION # login to server
+# FUNCTION # list servers
 ##############################
-function login() {
-    server=(${server_list[$1]})
-    v5NZ8jBr2HoQYD=${server[5]}
-    zodVApcRdLi4Kz=$(printf '%s' "$v5NZ8jBr2HoQYD" | base64 --decode)
-    pem="$zodVApcRdLi4Kz"
-    printf "${Blue}$USER${ResetColor} ${Green}logging${ResetColor} into the${Yellow}【${server[1]}】${ResetColor}server" | toilet -f term -F border
-	command="
-        expect {
-                \"*assword\" {set timeout 6000; send \"$pem\n\"; exp_continue ; sleep 3; }
-                \"*passphrase\" {set timeout 6000; send \"$pem\r\n\"; exp_continue ; sleep 3; }
-                \"yes/no\" {send \"yes\n\"; exp_continue;}
-                \"Last*\" {  send_user \"\nsuccessfully logined 【${server[1]}】\n\";}
-        }
-       interact
-    ";
-   if [ -f "$pem" ]
-   then
-	expect -c "
-		spawn ssh -p ${server[2]} -i $pem ${server[3]}@${server[2]}
-		${command}
-	"
-   else
-	expect -c "
-		spawn ssh -p ${server[3]} ${server[4]}@${server[2]}
-		${command}
-	"
-   fi
-    printf "${Blue}$USER${ResetColor} ${Red}logged out${ResetColor} the${Yellow}【${server[1]}】${ResetColor}server" | toilet -f term -F border
+function list() {
+    Close=1; Fit=20; bcount "Index\tDescription\tHost\tPort\tUsername\tPass|SecretKFile" && banner "${Red}Index\t${Green}Description\t${Blue}Host\tPort\tUsername\tPass|SecKFile${ResetColor}"
+    for ((i=0;i<"$server_list_length";i++));do
+        servers=(${server_list[$i]})
+        Close=0; banner "${Red}${servers[0]}${ResetColor}\t${Green}${servers[1]}${ResetColor}\t${servers[2]}\t${servers[3]}\t${servers[4]}\t${servers[5]}"
+    done
+    exit 0
 }
 
 ##############################
@@ -118,7 +113,6 @@ function login() {
 ##############################
 function create() {
 printf "\n${Blue}Creating a new server:${ResetColor}\n"
-#number=$(ls ~/.ssha | wc -l | tr -d '[:blank:]')
 printf "${Yellow}Please type the '${Blue}Description${Yellow}' of this server:${ResetColor}\n"
 read -r name
 printf "${Yellow}Please type the '${Blue}Hostname|IP${Yellow}' of this server:${ResetColor}\n"
@@ -142,10 +136,10 @@ printf "${Yellow}Password/Key (hidden):${Green} $pass ${ResetColor}\n"
 printf "\n${Blue}Informations is correct ?! (Y/N)${ResetColor}\n"
 read -r info
 if [[ "$info" =~ ^[yYoO] ]]; then
-	printf "\n${Green}'OK' ${Blue}Added server $name to the list${ResetColor}\n"
-	printf "Index=$server_list_length\nName=$name\nHost=$host\nPort=$port\nUser=$user\nPasswordOrKey=$v5NZ8jBr2HoQYD\n" | tee -a ~/.ssha/"$server_list_length"_"$name".conf
+	printf "Index=$server_list_length\nName=$name\nHost=$host\nPort=$port\nUser=$user\nPasswordOrKey=$v5NZ8jBr2HoQYD\n" > ~/.ssha/"$server_list_length"_"$name".conf
     chmod 700 ~/.ssha/"$server_list_length"_"$name".conf
-    printf "\n${Blue}Congratulations the server${Green} '$name' ${Blue}is well registered. ${ResetColor}Here is the current list of your servers:\n" | toilet -f term -F border
+    Close=1; Fit=4; bcount "Congratulations the server '$name' is well registered. Here is the current list of your servers:"
+    banner "${Blue}Congratulations the server${Green} '$name' ${Blue}is well registered. ${ResetColor}Here is the current list of your servers:"
     ssha -l
     exit 0
 elif [[ "$info" =~ ^[nN] ]]; then
@@ -163,17 +157,16 @@ fi
 function delete() {
 # see list of servers
 ssha -l
-#number=$(ls ~/.ssha | wc -l | tr -d '[:blank:]')
 printf "\n${Blue}Which server do you want to delete ? ${Yellow}(Enter the number)${ResetColor}\n"
 read -r srvnb
-if [[ ! $srvnb -lt $server_list_length ]]; then
+if [[ ! "$srvnb" < "$server_list_length" ]]; then
 printf "\n${Red}'INPUT ERROR' ${Blue}Exit${ResetColor}\n"
 exit 1
 else
 printf "\n${Blue}You have selected the server ${Green}$srvnb${Blue}. Do you really want to delete this server ? (Y/N)${ResetColor}\n"
     read -r info
     if [[ "$info" =~ ^[yYoO] ]]; then
-    printf "\n${Green}'OK' ${Blue}Server number ${Green}$srvnb ${Blue}is deleted${ResetColor}\n"
+    Close=1; Fit=4; bcount "'OK' Server number $srvnb is deleted" && banner "${Green}'OK' ${Blue}Server number ${Green}$srvnb ${Blue}is deleted${ResetColor}"
     rm ~/.ssha/$srvnb*
     mkdir $DeletedFolder
     # call binary to check deleted folder and re order servers list & exit 0
@@ -181,11 +174,44 @@ printf "\n${Blue}You have selected the server ${Green}$srvnb${Blue}. Do you real
     elif [[ "$info" =~ ^[nN] ]]; then
         printf "\n${Green}'OK' ${Blue}Go restart delete server${ResetColor}\n"
         ssha -d
-            else
-                printf "\n${Red}'INPUT ERROR' ${Blue}Exit${ResetColor}\n"
-                exit 1
+        else
+        printf "\n${Red}'INPUT ERROR' ${Blue}Exit${ResetColor}\n"
+        exit 1
     fi
 fi
+}
+
+##############################
+# FUNCTION # login to server
+##############################
+function login() {
+    server=(${server_list[$1]})
+    v5NZ8jBr2HoQYD=${server[5]}
+    zodVApcRdLi4Kz=$(printf '%s' "$v5NZ8jBr2HoQYD" | base64 --decode)
+    pem="$zodVApcRdLi4Kz"
+    Close=1; Fit=6; bcount "$USER logging into the【${server[1]}】server" && banner "${Blue}$USER${ResetColor} ${Green}logging${ResetColor} into the${Yellow}【${server[1]}】${ResetColor}server"
+	command="
+        expect {
+                \"*assword\" {set timeout 6000; send \"$pem\n\"; exp_continue ; sleep 3; }
+                \"*passphrase\" {set timeout 6000; send \"$pem\r\n\"; exp_continue ; sleep 3; }
+                \"yes/no\" {send \"yes\n\"; exp_continue;}
+                \"Last*\" {  send_user \"\nsuccessfully logined 【${server[1]}】\n\";}
+        }
+       interact
+    ";
+   if [ -f "$pem" ]
+   then
+	expect -c "
+		spawn ssh -p ${server[2]} -i $pem ${server[3]}@${server[2]}
+		${command}
+	"
+   else
+	expect -c "
+		spawn ssh -p ${server[3]} ${server[4]}@${server[2]}
+		${command}
+	"
+   fi
+    Close=1; Fit=6; bcount "$USER logged out the【${server[1]}】server" && banner "${Blue}$USER${ResetColor} ${Red}logged out${ResetColor} the${Yellow}【${server[1]}】${ResetColor}server"
 }
 
 ##############################
